apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalogue
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NagineniHari/Catalogue-Deploy.git
    targetRevision: main
    path: .
    helm:
      releaseName: catalogue
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
