apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: catalogue
  namespace: argocd
spec:
    project: default
    source:
      repoURL: https://github.com/NagineniHari/EKS-argoCD.git
      targetRevision: main
      path: .
      helm:
        releaseName: catalogue
        valueFiles:
          - values-dev.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true ## if you delete from Git, argocd also deletes it from cluster
        selfHeal: true ## Revert the changes that were done manually in cluster, to sync git repo